<?php

echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "\n";
echo "<head>\n";
echo "<title>Sebbyland</title>\n";
echo "<meta charset=\"utf-8\">\n";
echo "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
echo "<meta name=\"description\" content=\"Music template project\">\n";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/bootstrap-4.1.2/bootstrap.min.css\">\n";
echo "<link href=\"plugins/font-awesome-4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.3.4/owl.carousel.css\">\n";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.3.4/owl.theme.default.css\">\n";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.3.4/animate.css\">\n";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/main_styles.css\">\n";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/responsive.css\">\n";
echo "</head>\n";
echo "<?php\n";
echo "    header('X-Frame-Options: GOFORIT'); \n";
echo "?>\n";
echo "<body style=\"background-color:#001e73; z-index:-2;\">\n";
echo "<div class=\"count-particles\" style=\"z-index: -1; width: 100%; height: 100%;\">\n";
echo "  <span class=\"js-count-particles\" style=\"z-index: -1; width: 100%; height: 100%;\"></span>\n";
echo "</div>\n";
echo "<div class=\"count-particles\" style=\"z-index: -1; width: 100%; height: 100%;\">\n";
echo "  </div>\n";
echo "	<canvas id=\"drifter\" style=\"z-index: -1; position: fixed; width: 100%; height: 100%;\" ></canvas>\n";
echo "	<div id=\"particles-js\" style=\"z-index: -1;position: fixed; width: 100%; height: 100%;\"><canvas class=\"particles-js-canvas-el\"  style=\"width: 100%; height: 100%;\"></canvas></div>\n";
echo "	\n";
echo "<div class=\"super_container\">\n";
echo "	\n";
echo "	<!-- Header -->\n";
echo "\n";
echo "	<header class=\"header\">\n";
echo "		<div class=\"container\">\n";
echo "			<div class=\"row\">\n";
echo "				<div class=\"col\">\n";
echo "					<div class=\"header_content d-flex flex-row align-items-center justify-content-center\">\n";
echo "\n";
echo "					<!-- Logo -->\n";
echo "						<div class=\"logo\">\n";
echo "							<a href=\"#\" class=\"d-flex flex-row align-items-end justify-content-start\">\n";
echo "								<span class=\"logo_bars d-flex flex-row align-items-end justify-content-between\"><span></span><span></span><span></span><span></span><span></span></span>\n";
echo "								<span class=\"logo_text\">SebbyLand</span>\n";
echo "							</a>\n";
echo "						</div>\n";
echo "\n";
echo "						<!-- Main Navigation -->\n";
echo "						<nav class=\"main_nav\">\n";
echo "							<ul class=\"d-flex flex-row align-items-center justify-content-start\">\n";
echo "								<li><a href=\"home.html\">Home</a></li>\n";
echo "								<li><a href=\"artist.html\">Games</a></li>\n";
echo "								<li class=\"active\"><a href=\"http://mag1182.com/Proxy.html\">Proxy</a></li>\n";
echo "								<li><a href=\"blog.html\">News</a></li>\n";
echo "								<li><a href=\"http://mc.mag1182.com\">Contact</a></li>\n";
echo "							</ul>\n";
echo "						</nav>\n";
echo "\n";
echo "						\n";
echo "					</div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "		</div>\n";
echo "	</header>\n";
echo "\n";
echo "	<!-- Menu -->\n";
echo "\n";
echo "\n";
echo "	<div class=\"menu\">\n";
echo "		<div class=\"menu_container\">\n";
echo "			<div class=\"menu_background\"></div>\n";
echo "			<div class=\"menu_close\"><i class=\"fa fa-times\" aria-hidden=\"true\"></i></div>\n";
echo "			<div class=\"menu_content d-flex flex-column align-items-center justify-content-start\">\n";
echo "						<nav class=\"main_nav\">\n";
echo "							<ul class=\"d-flex flex-row align-items-center justify-content-start\">\n";
echo "								<li><a href=\"home.html\">Home</a></li>\n";
echo "								<li><a href=\"artist.html\">Games</a></li>\n";
echo "								<li class=\"active\"><a href=\"http://mag1182.com/Proxy.html\">Proxy</a></li>\n";
echo "								<li><a href=\"blog.html\">News</a></li>\n";
echo "								<li><a href=\"http://mc.mag1182.com\">Contact</a></li>\n";
echo "							</ul>\n";
echo "						</nav>\n";
echo "			</div>\n";
echo "		</div>\n";
echo "	</div>\n";
echo "\n";

echo "	<div style=
\"
padding-top: 135px;
    background-color: #2121218c;
    height: 400px;
    padding-left: 20px;
    padding-right: 20px;
    border-bottom: #2ac275;
    border-style: dashed;
    border-left-style: none;
    border-right-style: none;
    border-top-style: none;
	\"
	>\n";

echo file_get_contents('http://proxy.mag1182.com');

echo "	</div>\n";

echo "\n";
echo "			</div>\n";
echo "\n";
echo "		\n";
echo "\n";
echo "			<!-- Scroll Down -->\n";
echo "			<div class=\"scroll_down scroll_down_link\" data-scroll-to=\".tours\">\n";
echo "				<a href=\"#\"></a>\n";
echo "				<div class=\"d-flex flex-row align-items-center justify-content-start\">\n";
echo "					<div>scroll down</div>\n";
echo "					<div class=\"scroll_arrows d-flex flex-column align-items-start justify-content-start\">\n";
echo "						<img src=\"images/arrow_down.png\" alt=\"\">\n";
echo "						<img src=\"images/arrow_down.png\" alt=\"\">\n";
echo "					</div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "\n";
echo "	<div class=\"song\">\n";
echo "		<div class=\"parallax_background parallax-window\" data-parallax=\"scroll\" data-image-src=\"images/song.jpg\" data-speed=\"0.8\"></div>\n";
echo "		<div class=\"container\">\n";
echo "			<div class=\"row\">\n";
echo "				<div class=\"col\">\n";
echo "					<div class=\"song_content\">\n";
echo "\n";
echo "						<!-- Player -->\n";
echo "						<div class=\"single_player_container\">\n";
echo "							<div class=\"single_player d-flex flex-row align-items-center justify-content-start\">\n";
echo "								<div id=\"jplayer_1\" class=\"jp-jplayer\"></div>\n";
echo "								<div id=\"jp_container_1\" class=\"jp-audio\" role=\"application\" aria-label=\"media player\">\n";
echo "									<div class=\"jp-gui jp-interface d-flex flex-lg-row flex-column align-items-start justify-content-start\">\n";
echo "\n";
echo "										<!-- Player Controls -->\n";
echo "										<div class=\"player_controls_box d-flex flex-row align-items-start justify-content-start\">\n";
echo "											<div class=\"order-lg-1 order-2\">\n";
echo "												<div class=\"player_title\">Insurgence</div>\n";
echo "												<div class=\"jp-controls-holder player_controls ml-auto d-flex flex-row align-items-start justify-content-start\">\n";
echo "													<button class=\"jp-play player_button\" tabindex=\"0\"></button>\n";
echo "													<button class=\"jp-stop player_button\" tabindex=\"0\"></button>\n";
echo "												</div>\n";
echo "											</div>\n";
echo "											<div class=\"song_image ml-lg-auto order-lg-2 order-1\"><img src=\"images/sebby.png\" alt=\"\"></div>\n";
echo "										</div>\n";
echo "\n";
echo "										<!-- Progress Bar -->\n";
echo "										<div class=\"player_bars d-flex flex-row align-items-start justify-content-start\">\n";
echo "											<div class=\"player_progress_box\">\n";
echo "												<div class=\"jp-current-time\" role=\"timer\" aria-label=\"time\">00:00</div>\n";
echo "												<div class=\"song_info\">\n";
echo "													<div class=\"jp-artist\" aria-label=\"title\">Sebastian Robinson</div>\n";
echo "													<div class=\"jp-title\" aria-label=\"title\"></div>\n";
echo "												</div>\n";
echo "												<div class=\"jp-progress\">\n";
echo "													<div class=\"jp-seek-bar\">\n";
echo "														<div>\n";
echo "															<div class=\"jp-play-bar\"><span></span></div>\n";
echo "														</div>\n";
echo "													</div>\n";
echo "												</div>\n";
echo "												<div class=\"jp-duration ml-auto\" role=\"timer\" aria-label=\"duration\">02:33</div>\n";
echo "											</div>\n";
echo "\n";
echo "											<!-- Volume Controls -->\n";
echo "											<div class=\"jp-volume-controls ml-lg-auto\">\n";
echo "												<div class=\"mute_button\">\n";
echo "													<button class=\"jp-mute\" tabindex=\"0\"></button>\n";
echo "												</div>\n";
echo "												<div class=\"d-flex flex-row align-items-center justify-content-start\">\n";
echo "													<div class=\"jp-volume-bar\">\n";
echo "														<div>\n";
echo "															<div class=\"jp-volume-bar-value\"></div>\n";
echo "														</div>\n";
echo "													</div>\n";
echo "												</div>\n";
echo "											</div>\n";
echo "										</div>\n";
echo "										\n";
echo "									</div>\n";
echo "									<div class=\"jp-no-solution\">\n";
echo "										<span>Update Required</span>\n";
echo "										To play the media you will need to either update your browser to a recent version or update your <a href=\"http://get.adobe.com/flashplayer/\" target=\"_blank\">Flash plugin</a>\n";
echo "									</div>\n";
echo "								</div>\n";
echo "							</div>\n";
echo "						</div>\n";
echo "\n";
echo "					</div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "		</div>\n";
echo "	</div>\n";
echo "	\n";
echo "	<!-- App -->\n";
echo "\n";
echo "	<div class=\"app\">\n";
echo "		<div class=\"container\">\n";
echo "			<div class=\"row row-lg-eq-height\">\n";
echo "				\n";
echo "				<!-- App Image -->\n";
echo "				<div class=\"col-lg-6 order-lg-1 order-2 app_col\">\n";
echo "					<div class=\"app_image\">\n";
echo "						<img src=\"images/app.jpg\" alt=\"\">\n";
echo "					</div>\n";
echo "				</div>\n";
echo "\n";
echo "				<!-- App Content -->\n";
echo "				<div class=\"col-lg-6 order-lg-2 order-1\">\n";
echo "					<div class=\"app_content d-flex flex-column align-items-start justify-content-center\">\n";
echo "						<div class=\"section_title\"><h1>Play PolyRun on android today!</h1></div>\n";
echo "						<div class=\"app_text\">\n";
echo "							<p>PolyRun is in a vary early development state and will be updated a lot.<br>-Added new character<br>\n";
echo "-Added new menu<br></p>\n";
echo "						</div>\n";
echo "						<div class=\"stores d-flex flex-row align-items-start justify-content-start flex-wrap\">\n";
echo "							<!--<div class=\"store\"><a href=\"#\"><img src=\"images/appstore.png\" alt=\"\"></a></div>-->\n";
echo "							<div class=\"store\"><a href=\"https://play.google.com/apps/testing/com.Sebastan_Robinson.PolyRun\"><img src=\"images/googleplay.png\" alt=\"\"></a></div>\n";
echo "						</div>\n";
echo "					</div>\n";
echo "				</div>\n";
echo "\n";
echo "			</div>\n";
echo "		</div>\n";
echo "	</div>\n";
echo "\n";
echo "\n";
echo "	<footer class=\"footer\">\n";
echo "		<div class=\"background_image\" style=\"\"></div>\n";
echo "		<div class=\"footer_content\">\n";
echo "			<div class=\"container\">\n";
echo "				<div class=\"row\">\n";
echo "					<div class=\"col text-center\">\n";
echo "\n";
echo "						<!-- Logo -->\n";
echo "						<div class=\"logo\">\n";
echo "							<a href=\"#\" class=\"d-flex flex-row align-items-end justify-content-start\">\n";
echo "								<span class=\"logo_bars d-flex flex-row align-items-end justify-content-between\"><span></span><span></span><span></span><span></span><span></span></span>\n";
echo "								<span class=\"logo_text\">SebbyLand</span>\n";
echo "							</a>\n";
echo "						</div>\n";
echo "\n";
echo "						\n";
echo "					</div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "		</div>\n";
echo "		<div class=\"footer_bar\">\n";
echo "			<div class=\"container\">\n";
echo "				<div class=\"row\">\n";
echo "					<div class=\"col\">\n";
echo "						<div class=\"copyright text-center\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n";
echo "Copyright ©<script>document.write(new Date().getFullYear());</script> All rights reserved by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n";
echo "<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>\n";
echo "					</div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "		</div>\n";
echo "			\n";
echo "	</footer>\n";
echo "\n";
echo "\n";
echo "<script src=\"js/jquery-3.3.1.min.js\"></script>\n";
echo "<script src=\"styles/bootstrap-4.1.2/popper.js\"></script>\n";
echo "<script src=\"styles/bootstrap-4.1.2/bootstrap.min.js\"></script>\n";
echo "<script src=\"plugins/greensock/TweenMax.min.js\"></script>\n";
echo "<script src=\"plugins/greensock/TimelineMax.min.js\"></script>\n";
echo "<script src=\"plugins/scrollmagic/ScrollMagic.min.js\"></script>\n";
echo "<script src=\"plugins/greensock/animation.gsap.min.js\"></script>\n";
echo "<script src=\"plugins/greensock/ScrollToPlugin.min.js\"></script>\n";
echo "<script src=\"plugins/OwlCarousel2-2.3.4/owl.carousel.js\"></script>\n";
echo "<script src=\"plugins/jPlayer/jquery.jplayer.min.js\"></script>\n";
echo "<script src=\"plugins/jPlayer/jplayer.playlist.min.js\"></script>\n";
echo "<script src=\"plugins/easing/easing.js\"></script>\n";
echo "<script src=\"plugins/progressbar/progressbar.min.js\"></script>\n";
echo "<script src=\"plugins/parallax-js-master/parallax.min.js\"></script>\n";
echo "<script src=\"plugins/scrollTo/jquery.scrollTo.min.js\"></script>\n";
echo "<script src=\"js/custom.js\"></script>\n";
echo "	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/1.20.2/TweenMax.min.js\"></script>\n";
echo "	\n";
echo "	\n";
echo "	<script src=\"js/dependencies.js\"></script>\n";
echo "	<script src=\"js/backgrounds/drifter.min.js\"></script>\n";
echo "	<script src=\"js/backgrounds/particles.min.js\"></script>\n";
echo "	<script src=\"js/main.js\"></script>\n";
echo "	<script src=\"../particles.js\"></script>\n";
echo "	<script src=\"js/Mainapp.js\"></script>\n";
echo "</body>\n";
echo "</html>";

?>
